version: '3.8'
services:
  ollama:
    hostname: ollama
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"

  ollama_api:
    build: .
    container_name: ollama_api
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    networks:
      - ollama_network
    environment:
      SPRING_AI_OLLAMA_URL: http://ollama:11434

networks:
  ollama_network:
    driver: bridge
